spring:
  application:
    name: key-nest
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope: profile,email
            client-name: Google

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
